####
# mvn package -Pnative -Dquarkus.native.container-build=true
# docker build -f src/main/docker/Dockerfile.native -t daggerok/native-app .
# docker run -i --rm -p 8080:8080 -v "$(pwd)/src/main/resources/templates:/work/templates" daggerok/native-app
###
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
